version: 2.1

orbs:
  python: circleci/python@1.5.0
  
jobs:
  build_and_test:
    docker:
      - image: cimg/python:3.10.1
    steps:
      - checkout
      - python/install-packages:
         pkg-manger: pip
      - run:
         name: Run tests
         command: python -m pytest
      - persist_to_workspace:
         root: ~/project
         paths:
           - .
workflows:
  build_test_deploy:
    jobs:
      - build_and_test
  
