version: 2.1

orbs:
  python: circleci/python@1.5.0
  
jobs:
  build_and_test:
    docker:
      - image: cimg/python:3.10.1
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pipenv
      - run:
          name: Run tests
          command: pipenv run python manage.py test
      - store_test_results:
          path: test-results
      - persist_to_workspace:
          root: ~/project
          paths:
            - .
workflows:
  build_test_deploy:
    jobs:
      - build_and_test
  
